### ISSUE TITLE
std::gmtime is now deprecated. 

### ISSUE THREAD

**Issue by Cruton45** [DnA-IntRicate/ImGuiDatePicker#2]
I am using latest c++ release and std::gmtime is now deprecated and is throwing a warning. I fixed this just by switching to gmtime_s. Like I said I am not using c++20, I am using the latest but I figured I would through this out there. Other than that using latest as of now works fine.

Usage of std::gmtime on line 157 in Today().

**Comment by DnA-IntRicate** [comment]
Hi there, thank you for reporting the issue and apologies for addressing it so late.

I'm going to commit the fix now.
